---
- name: Reset Kubernetes component
  become: true
  ansible.builtin.command: kubeadm reset --force
  changed_when: true

- name: Install kubectl
  ansible.builtin.apt:
    name: kubectl

- name: Init kubeadm
  become: true
  ansible.builtin.command: kubeadm init
  changed_when: true

- name: Create .kube folder
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy kubeconfig
  ansible.builtin.copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
