---
- name: Install pre-requisites
  hosts: all
  become: true
  tasks: []
  roles:
    - role: prepare-cluster

- name: Initialize controlplanes
  hosts: controlplanes
  become: true
  tasks: []
  roles:
    - role: master

- name: Initialize Nodes
  hosts: nodes
  become: true
  tasks: []
  roles:
    - role: node

- name: Install CNI
  hosts: controlplanes
  become: true
  tasks: []
  roles:
    - role: weave

- name: Restart kubelet
  hosts: all
  become: true
  tasks:
    - name: Enable service kubelet
      become: true
      ansible.builtin.service:
        name: kubelet
        enabled: true
